# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-18 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': '1. Turnos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set([('nombre', 'abreviatura')]),
        ),
    ]
