# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteadmision',
            name='usuario_creacion',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_pacienteadmision_usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pacienteatencion',
            name='paciente_consulta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='paciente_pacienteatencion_paciente_consulta', to='paciente.PacienteConsulta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacienteatencion',
            name='usuario_creacion',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_pacienteatencion_usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pacienteciex',
            name='paciente_consulta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='paciente_pacienteciex_paciente_consulta', to='paciente.PacienteConsulta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacienteciex',
            name='usuario_creacion',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_pacienteciex_usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pacientecif',
            name='paciente_consulta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='paciente_pacientecif_paciente_consulta', to='paciente.PacienteConsulta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientecif',
            name='usuario_creacion',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_pacientecif_usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
