# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20161222_1326'),
        ('paciente', '0002_auto_20161222_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientecita',
            name='disponibilidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='paciente_pacientecita_disponibilidad', to='users.UserDisponibilidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientecita',
            name='paciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='paciente_pacientecita_paciente', to='paciente.PacienteAdmision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientecita',
            name='usuario_creacion',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_pacientecita_usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
